services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/site
      - bundle_cache:/usr/local/bundle
    command: bundle exec jekyll serve --host 0.0.0.0 --config _config.yml,_config.dev.yml --livereload

volumes:
  bundle_cache:
